// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ny8ntvENInGZMCAZGXeWZ8YwgWYFbTs',
    appId: '1:609253172237:web:a9073936b29f517ff02144',
    messagingSenderId: '609253172237',
    projectId: 'profileapp-project',
    authDomain: 'profileapp-project.firebaseapp.com',
    storageBucket: 'profileapp-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDryTTGRGKQ0K6Baz83KUvTNxKWhqP7S10',
    appId: '1:609253172237:android:44d0cf57bf391a9af02144',
    messagingSenderId: '609253172237',
    projectId: 'profileapp-project',
    storageBucket: 'profileapp-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxeN0ZZn3flj4gn2VIeqVlxnwp1H7Ehuw',
    appId: '1:609253172237:ios:1374a8345a40d520f02144',
    messagingSenderId: '609253172237',
    projectId: 'profileapp-project',
    storageBucket: 'profileapp-project.firebasestorage.app',
    iosBundleId: 'com.example.profileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxeN0ZZn3flj4gn2VIeqVlxnwp1H7Ehuw',
    appId: '1:609253172237:ios:1374a8345a40d520f02144',
    messagingSenderId: '609253172237',
    projectId: 'profileapp-project',
    storageBucket: 'profileapp-project.firebasestorage.app',
    iosBundleId: 'com.example.profileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ny8ntvENInGZMCAZGXeWZ8YwgWYFbTs',
    appId: '1:609253172237:web:ec356128ac65436ff02144',
    messagingSenderId: '609253172237',
    projectId: 'profileapp-project',
    authDomain: 'profileapp-project.firebaseapp.com',
    storageBucket: 'profileapp-project.firebasestorage.app',
  );
}
